config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about_me', to: 'welcome#about'
  get('/contact_me',{to: 'contacts#index'})
  post('/contact_me', {to: 'contacts#create'})
  resources :poems
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
  def create
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @email = params[:email]
    @text = params[:text]
    ContactMeMailer.message_for_you(@first_name,@last_name,@email,@text).deliver_now
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  def new
    @poem = Poem.new
  end
  def index
    @poems = Poem.order(created_at: :desc)
  end
  def create
    poems_params = params.require(:poem).permit([:name, :description])
    @poem = Poem.new poems_params
    if @poem.save
    redirect_to poems_path
    else
    render :new
    end
  end
  def show
    @poem = Poem.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1> Ciarra glass got your message</h1>

app/views/contacts/index.html.erb
<body id='Contact_me_body'>
<div class="columns">
<div class="column" id="firstColumn">
  <div class="field">
  <%= form_tag contact_me_path do %>
  <strong class="label" ><%= label_tag :firstname %></strong>
  <%= text_field_tag :first_name,'',class: "input is-medium",id: 'input_name',placeholder:"First Name"  %>
  <strong class="label" ><%= label_tag :lastname %></strong>
  <%= text_field_tag :last_name,'',class: "input is-medium",id: 'input_name',placeholder:"last Name"  %>
  <strong class="label"><%= label_tag :email  %></strong>
  <%= email_field_tag :email,'',class: 'input is-medium ',id: 'input_email',placeholder:"Email" %>
  <strong class="label"><%= label_tag :text  %></strong>
  <%= text_area_tag :text,'',class: 'textarea',id: 'input_text',placeholder:'Text' %>
  <div id="SubmitContainer">
  <%= submit_tag 'Submit', class: 'button is-medium is-fullwidth',id:'SubmitButton' %>
  </div>
 </div>
</div>
 <div class="column">
 </div>
 <div class="column">
 </div>
</div>
<% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
  .navbar-item{
    font-size: 20px;
    font-weight: bold;
    color: white;
    font-family: cursive;
  }
  </style>
  <body>
    <nav class="navbar" id="navbar">
      <%= link_to 'Home', root_path,class:'navbar-item', id:'home'%>
      <%= link_to 'About Me', about_me_path,class:'navbar-item' %>
      <%= link_to 'Contact me', contact_me_path,class:'navbar-item' %>
      <%= link_to 'Poems', poems_path,class:'navbar-item' %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/poems/index.html.erb
<div class="grid-container">
  <% @poems.each do |poem| %>
  <div class="grid-item">
    <img src="https://pay.google.com/about/static/images/social/knowledge_graph_logo.png"></img>
    <h6><strong>Name:</strong> <%= link_to poem.name,poem_path(poem),id:'Name' %></h6>
    <% if poem.description.length < 40 %>
      <p><strong>The poem: </strong><%= poem.description %></p>
      <% else %>
      <p><strong>The poem: </strong><%= poem.description[0...40].insert(40,'....')%></p>
      <% end %>
    </div>
<% end %>
</div>

app/views/poems/new.html.erb
<h1> New poem </h1>
<%= form_for @poem do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<hr/>
<%= f.label :description %>
<%= f.text_area :description,class:'textarea'%>
<%= f.submit %>
<% end %>

app/views/poems/show.html.erb
<body id="ShowBody">
  <div class="columns">
    <div class="column">
    </div>
    <div class="column">
<h1><%= @poem.name %></h1>
<p><%= @poem.description %> </p>
</div>
<div class="column">
</div>
</div>
</body>

app/views/welcome/about.html.erb
<body id="AboutMeBody">
  <div class="AboutMeContainer">
    <h1> About Me</h1>
    <span class="border"></span>
    <div class="image">
      <!-- <%= fa_icon "fas fa-user-md 5x", class:"fas fa-user-md" %> -->
      <a><img src="https://r.hswstatic.com/w_907/gif/tesla-cat.jpg"></a>
    </div>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
</div>
</body>

app/views/welcome/index.html.erb
<h1 class="title">Home Page</h1>